### ISSUE TITLE
Would a Rust port for this project be possible at all?

### ISSUE THREAD

**Issue by mtx2d** [netwarm007/GameEngineFromScratch#20]
Dear Team,
This is an amazing project. 
Thanks for putting so much effort to make this tutorial a reality in the first place!

I like this project so I want to follow along and create my own game at the end but I am really afraid of using C++ as the dev language because I do think I can do memory management correctly. 

In the mean time I am also aware that not all existing eco system is there for Rust so I wanted to know what is the most important support needed if I were to port this project from C++ to Rust?

I do not know either language well so my question is probably too much of an ask. 
Can someone please with enough context either help me find the minimum set of work needs to be done or help me ask the right question?

Thanks in advance, really appreciate the work here, I am already grateful for what the project has been offering at the moment.

**Comment by netwarm007** [comment]
Hi mtx2d

Thank you for your love of my project.

Personally I only with few experience with Rust, but since it is also a system programming language and supports C ABI, so in theory you will find nothing stops you.

Since most graphic APIs are provided as C libraries, you will have to warp them in order to use them in Rust, I think that is the biggest effort. But since those APIs are very common, maybe some one has already done that. So, please try to do a search before go ahead.

For physic simulation part, boost is my choice and it is also written in C. So rust should be able to do a FFI call to it simply, and again, it is a famous library so rust wrapper may already exists.

I think most C++ are written by me (all other dependencies are mostly in C) so defiantly you can rewrite it to Rust.

Good luck!

2020年5月14日 07:03，mtx2d <notifications@github.com<mailto:notifications@github.com>> 写道：



Dear Team,
This is an amazing project.
Thanks for putting so much effort to make this tutorial a reality in the first place!

I like this project so I want to follow along and create my own game at the end but I am really afraid of using C++ as the dev language because I do think I can do memory management correctly.

In the mean time I am also aware that not all existing eco system is there for Rust so I wanted to know what is the most important support needed if I were to port this project from C++ to Rust?

I do not know either language well so my question is probably too much of an ask.
Can someone please with enough context either help me find the minimum set of work needs to be done or help me ask the right question?

Thanks in advance, really appreciate the work here, I am already grateful for what the project has been offering at the moment.

**Comment by netwarm007** [comment]
Just to correct, physic part is bullet, not boost. :)

**Comment by mtx2d** [comment]
Thanks a lot for the pointers!
Seem like most of the library can be reused by using C as the common layer to talk to each other.
